name: Docker Image CI

on:
  pull_request:
    branches: ["main"]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build backend image
        run: docker build ./codelabBackEnd -f ./codelabBackEnd/Dockerfile -t codelab-backend:${{ github.sha }}

      - name: Build frontend image
        run: docker build ./codelabFrontEnd -f ./codelabFrontEnd/Dockerfile -t codelab-frontend:${{ github.sha }}
